### ISSUE TITLE
Despite being logged in, tasks are not syncing via iCloud

### ISSUE THREAD

**Issue by keshaaaav** [rursache/ToDoList#17]
One more quick question, despite being logged in, tasks are not syncing via iCloud

Tasks:

![iPad - Tasks](https://user-images.githubusercontent.com/83570000/150647884-3dbb48fc-6b99-4043-a475-67d60400ee49.jpeg)

App Settings:

![iPad - Settings](https://user-images.githubusercontent.com/83570000/150647878-97e12fd0-59e8-459a-950d-a10d6797461c.jpg)

PS: I tried syncing manually too

Tasks:

![iPhone - Tasks](https://user-images.githubusercontent.com/83570000/150647883-8da173c3-5b46-4665-ae21-79ed8b5b0a6a.jpeg)

App Settings:

![iPhone - Settings](https://user-images.githubusercontent.com/83570000/150647872-bc8f8407-aca8-434d-a1ee-1074eca6eea2.jpg)

_Originally posted by @keshaaaav in https://github.com/rursache/ToDoList/issues/16#issuecomment-1019307501_

**Comment by rursache** [comment]
there are multiple things to keep in mind here:

0. Make sure you are logged into the same iCloud account on both devices and that the app is allowed to store data in your iCloud drive
1. If you cloned the repo and ran the app locally on your devices, make sure you added a valid iCloud container in the project. the AppStore version should be fine OOB
2. Syncing depends on the very 'fragile' iCloud infrastructure that keeps breaking since the beginning of the year. More and more developers reports that syncing is unreliable and its nothing we can do (see tweetbot's dev tweets). Hopefully Apple will do something about it
3. You can debug syncing by watching what IceCream (the SDK used to auto-sync realm dbs) does
4. Initial sync is slower so you could take a look tomorrow and see if everything is fine

I will close this issue for now
